name: ci

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  get_versions:
    uses: ./.github/workflows/get-versions.yml

  display_versions:
    name: Display versions
    runs-on: ubuntu-latest
    needs: [get_versions]
    steps:
      - name: Display versions
        run: |
          echo "PostgreSQL version: ${{ needs.get_versions.outputs.postgres_version }}"
          echo "pgvector version: ${{ needs.get_versions.outputs.pgvector_version }}"
