name: ci

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:

  get_versions:
    name: Get versions
    uses: ./.github/workflows/get-versions.yml
    outputs:
      postgres_version: ${{ steps.get_versions.outputs.postgres_version }}
      pgvector_version: ${{ steps.get_versions.outputs.pgvector_version }}

  display_versions:
    name: Display versions
    runs-on: ubuntu-latest
    needs: get_versions
    steps:
      - name: Display versions
        run: |
          echo "PostgreSQL version: ${{ needs.get_versions.outputs.postgres_version }}"
          echo "pgvector version: ${{ needs.get_versions.outputs.pgvector_version }}"
