name: get-versions

on:
  workflow_call:
    outputs:
      postgres_version:
        value: ${{ jobs.get_versions.outputs.postgres_version }}
      pgvector_version:
        value: ${{ jobs.get_versions.outputs.pgvector_version }}

permissions:
  contents: read

jobs:
  get_versions:
    name: Get versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get postgres version from tag
        run: |
          tag = $(echo "${{ github.ref_name }}" | grep '^[0-9]*.[0-9]*.[0-9]*_[0-9]*.[0-9]*.[0-9]*$') || true
          version=$(echo "$tag" | awk -F'[._]' '{print $1"."$2"."$3}') || true

          if [ -z "$version" ]; then
            # Set default version for non-release builds
            version="16.2.0"
          fi
          echo "POSTGRESQL_VERSION=$version" | tee -a $GITHUB_ENV

      - name: Get pgvector version from tag
        run: |
          tag = $(echo "${{ github.ref_name }}" | grep '^[0-9]*.[0-9]*.[0-9]*_[0-9]*.[0-9]*.[0-9]*$') || true
          version=$(echo "$tag" | awk -F'[._]' '{print $4"."$5"."$6}') || true

          if [ -z "$version" ]; then
            # Set default version for non-release builds
            version="0.7.0"
          fi

          echo "PGVECTOR_VERSION=$version" | tee -a $GITHUB_ENV
          
    outputs:
      postgres_version: ${{ env.POSTGRESQL_VERSION }}
      pgvector_version: ${{ env.PGVECTOR_VERSION }}
