name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+_[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Get the release version from the tag
        if: env.VERSION == ''
        run: echo "VERSION=${{ github.ref_name }}" | tee -a $GITHUB_ENV
      - name: Display the version
        run: |
          echo "version is: $VERSION"
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${VERSION}" --draft --verify-tag --title $VERSION
    outputs:
      version: ${{ env.VERSION }}

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      release: true

  publish_release:
    name: Publish Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Get the release version from the tag
        if: env.VERSION == ''
        run: echo "VERSION=${{ github.ref_name }}" | tee -a $GITHUB_ENV
      - name: Display the version
        run: |
          echo "version is: $VERSION"
      - name: Publish GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit "${VERSION}" --draft=false
    outputs:
      version: ${{ env.VERSION }}
