name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+_[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      release: true
